.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. ubicoin_qt test_ubicoin_qt
clean: FORCE
	$(MAKE) -C .. ubicoin_qt_clean test_ubicoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_ubicoin_qt_check
ubicoin-qt ubicoin-qt.exe: FORCE
	 $(MAKE) -C .. ubicoin_qt
